### ISSUE TITLE
invalid headless cms

### ISSUE THREAD

**Issue by richtong** [privatemaker/headless-cms#3]
Is this project being maintained? I'm happy to help if not, I tried to do the basics

My hugo.yaml 

```
baseURL: /
languageCode: en-us
title: My New Hugo Site
# if you have a submodule use this in ./themes
# theme: hugo-universal-theme
# if you are using hugo modules, use this and
module:
  imports:
    # - path: github.com/devcows/hugo-universal-theme
    # - path: github.com/theNewDynamic/gohugo-theme-ananke
    # - path: github.com/richtong/hugo-universal-theme
    # this does not work well because go.mod insists on different name
    - path: github.com/richtong/gohugo-theme-ananke
    # hugolify failing on local repo edits
    # - path: github.com/hugolify/hugolify-sveltia-cms
    - path: github.com/privatemaker/headless-cms

outputs:
  home:
    - HTML
    - RSS
    - HeadlessCMSConfig
params:
  headless-cms:
    engine: sveltia
    site_url: https://tongfamily.com
    backend:
      name: github
      repo: richtong/web-hugo
    collections:
      blog:
        create: true
        fields:
          - label: Title
            name: Name
            widget: String

```

Which is just copied from you. But I'm getting an error says the engine is not recognized? I tried decap as well.

![image](https://github.com/user-attachments/assets/1d7d478f-252c-4d27-abf0-60cfc80e0255)
